kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '20'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"tgis"},"name":"tgis-deployment","namespace":"tgi"},"spec":{"progressDeadlineSeconds":600,"replicas":0,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"tgis"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"tgis"}},"spec":{"containers":[{"args":["--model-id","mosaicml/mpt-7b-instruct","--num-shard","1","--max-total-tokens","2048","--max-input-length","1600","--trust-remote-code","--port","8048"],"env":[{"name":"LOG_LEVEL","value":"debug"}],"image":"ghcr.io/huggingface/text-generation-inference:latest","imagePullPolicy":"Always","name":"tgis","ports":[{"containerPort":8048,"name":"runtime-rest","protocol":"TCP"}],"resources":{"limits":{"nvidia.com/gpu":"1"},"requests":{"cpu":"2","memory":"8Gi","nvidia.com/gpu":"1"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data","name":"data"},{"mountPath":"/.cache","name":"cache"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"nvidia.com/gpu","operator":"Exists"}],"volumes":[{"emptyDir":{"sizeLimit":"40Gi"},"name":"data"},{"emptyDir":{"sizeLimit":"40Gi"},"name":"cache"}]}}}}
  resourceVersion: '15902741'
  name: tgis-deployment
  uid: df625511-c282-40e8-b670-d87d5a975461
  creationTimestamp: '2023-09-15T18:07:14Z'
  generation: 65
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2023-09-15T18:07:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"tgis"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:env':
                    .: {}
                    'k:{"name":"LOG_LEVEL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8048,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:tolerations': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2023-10-13T21:34:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"tgis"}':
                  'f:args': {}
                  'f:resources':
                    'f:limits':
                      'f:nvidia.com/gpu': {}
                    'f:requests':
                      'f:nvidia.com/gpu': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/.cache"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/data"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/dev/shm"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
              'f:volumes':
                .: {}
                'k:{"name":"cache-volume"}':
                  .: {}
                  'f:emptyDir':
                    .: {}
                    'f:medium': {}
                    'f:sizeLimit': {}
                  'f:name': {}
                'k:{"name":"claim-cache"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"claim-data"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-10-13T21:34:40Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
      subresource: status
  namespace: tgi
  labels:
    app: tgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tgis
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tgis
    spec:
      volumes:
        - name: claim-data
          persistentVolumeClaim:
            claimName: claim-data
        - name: claim-cache
          persistentVolumeClaim:
            claimName: claim-cache
        - name: cache-volume
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      containers:
        - resources:
            limits:
              nvidia.com/gpu: '4'
            requests:
              cpu: '2'
              memory: 8Gi
              nvidia.com/gpu: '4'
          terminationMessagePath: /dev/termination-log
          name: tgis
          env:
            - name: LOG_LEVEL
              value: debug
          ports:
            - name: runtime-rest
              containerPort: 8048
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: claim-data
              mountPath: /data
            - name: claim-cache
              mountPath: /.cache
            - name: cache-volume
              mountPath: /dev/shm
          terminationMessagePolicy: File
          image: 'ghcr.io/huggingface/text-generation-inference:latest'
          args:
            - '--model-id'
            - codellama/CodeLlama-13b-hf
            - '--num-shard'
            - '4'
            - '--max-total-tokens'
            - '2048'
            - '--max-input-length'
            - '1600'
            - '--trust-remote-code'
            - '--port'
            - '8048'
            - '--max-batch-prefill-tokens'
            - '2048'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 65
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-10-13T21:34:23Z'
      lastTransitionTime: '2023-09-15T18:07:14Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "tgis-deployment-7c74ffbd6c" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-10-13T21:34:40Z'
      lastTransitionTime: '2023-10-13T21:34:40Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.


